export enum QueryError {
    NULL = "NULL",
    UNEXPECTEDRESULT = "UNEXPECTED RESULT",
    NORESULT = "NO RESULT",
    INSERTIONFAILED = "FAILED INSERTION",
    UPDATEFAILED = "FAILED UPDATE",
};

export enum JWTError {
    VERIFICATIONFAILED = "VERIFICATED FAILED",
    SIGNFAILED = "SIGN FAILED",
}

