export enum QueryError {
    NULL = "NULL",
    UNEXPECTEDRESULT = "UNEXPECTED RESULT",
    NORESULT = "NO RESULT",
    INSERTIONERROR = "FAILED INSERTION",
};

export enum JWTError {
    VERIFICATIONFAILED = "VERIFICATED FAILED",
    SIGNFAILED = "SIGN FAILED",
}

